export { default as Home } from './Home'
export { default as Profile } from './Profile'
export { default as Login } from './Auth/login'
export { default as Signup } from './Auth/signup'
export { default as Post } from './Posts/post'
